name: Testing Loggings in Deno

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    name: Testing Loggings in Deno
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test Loggings in Deno
        run: deno run --allow-all tests/index.ts --unstable-sloppy-imports
