name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Create release branch and bump version
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release/${REF:10}
          git config --local user.email "github@drylian.com.br"
          git config --local user.name "Loggings Releases"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/    "version": "canary",/    "version": "${REF:11}",/" package.json
          git add package.json
          git commit -m "New Loggings release inbound!"
          git push

      - name: Remove unnecessary files 
        run: | 
          rm -rf node_modules test tsconfig.json src docs package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}